### ISSUE TITLE
Hunt down array allocation in sweep loops

### ISSUE THREAD

**Issue by timtylin** [slimgroup/spot#5]
Ever since we got rid of pre-allocation in `applyMultiply` for operators with sweepflag `true`, the way that `multiply` was previously written in some operators would lead to arrays implicitly growing inside loops. This is the most common Matlab mistake and leads to exponential complexity in runtime.

I've fixed some in commit 6dd3deda0d, but we probably need to go around hunting down the rest of them.

**Comment by henryk-modzelewski** [comment]
It is an old one.:( Actually the loops have inverted indexing, so there is only one allocation.
